.TH TABELA_HASH 1
.SH NAME
tabelaHash.out \- Implementação em C para uma Tabela Hash com suporte à rehash e 4 métodos de tratamento de conflitos.
.SH SYNOPSIS
.B tabelaHash.out
.IR option
.SH DESCRIPTION
.B tabelaHash.out
Tabelha Hash implementada em C com suporte à 4 métodos de tratamento de conflitos e rehash.
.PP
Entradas aceitas consistem em \fBAÇÃO\fR \fBCHAVE\fR
Com \fBAÇÃO\fR podendo ser
        \fIINSERT\fR
        \fIGET\fR
        \fIDELETE\fR
.SH OPTIONS
.TP
.BR \-n ", " \-\-bits =\fIBITS\fR
Set the number of bits to modify.
Default is one bit.
